// src/lib/mood-data.ts
import { MoodContent, ShopItem } from '@/types';

// Sample content for each mood
export const moodContent: Record<string, MoodContent> = {
  happy: {
    title: 'Happy Vibes',
    emoji: '😊',
    quotes: [
      "Happiness is not something ready made. It comes from your own actions.",
      "The most wasted of all days is one without laughter.",
      "Happiness is when what you think, what you say, and what you do are in harmony.",
      "Count your age by friends, not years. Count your life by smiles, not tears.",
      "The purpose of our lives is to be happy."
    ],
    articles: [
      {
        id: 'happy-1',
        title: '10 Science-Backed Ways to Boost Your Happiness',
        excerpt: 'Research shows that certain activities can help increase your happiness levels naturally. From exercise to meditation, learn what works.',
        imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643',
        source: 'Positive Psychology',
        url: 'https://example.com/happy-article-1',
      },
      {
        id: 'happy-2',
        title: 'How Optimism Affects Your Health',
        excerpt: 'Studies show that optimistic people tend to have healthier hearts, lower blood pressure, and stronger immune systems.',
        imageUrl: 'https://images.unsplash.com/photo-1542224566-6e85f2e6772f',
        source: 'Health & Wellness',
        url: 'https://example.com/happy-article-2',
      },
      {
        id: 'happy-3',
        title: 'The Joy of Small Things',
        excerpt: 'Finding happiness doesn\'t always require grand gestures. Learn how to appreciate life\'s simple pleasures.',
        imageUrl: 'https://images.unsplash.com/photo-1551887196-72e32bfc7d91',
        source: 'Mindful Living',
        url: 'https://example.com/happy-article-3',
      },
    ],
    playlists: [
      {
        id: 'happy-playlist-1',
        name: 'Good Vibes Playlist',
        description: 'Upbeat songs that boost your mood and energy',
        coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7',
        sourceUrl: 'https://example.com/happy-playlist-1',
        source: 'Spotify',
      },
      {
        id: 'happy-playlist-2',
        name: 'Sunshine Pop Hits',
        description: 'Bright pop tunes guaranteed to make you smile',
        coverUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae',
        sourceUrl: 'https://example.com/happy-playlist-2',
        source: 'Apple Music',
      },
      {
        id: 'happy-playlist-3',
        name: 'Acoustic Joy',
        description: 'Mellow acoustic tracks with positive vibes',
        coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4',
        sourceUrl: 'https://example.com/happy-playlist-3',
        source: 'YouTube Music',
      },
      {
        id: 'happy-playlist-4',
        name: 'Dance Party',
        description: 'High-energy dance tracks to get you moving',
        coverUrl: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec',
        sourceUrl: 'https://example.com/happy-playlist-4',
        source: 'Spotify',
      },
    ],
    videos: [
      {
        id: 'happy-video-1',
        title: 'The Science of Happiness',
        thumbnailUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91',
        duration: '5:42',
        source: 'YouTube',
        url: 'https://example.com/happy-video-1',
      },
      {
        id: 'happy-video-2',
        title: '3-Minute Mood Booster Workout',
        thumbnailUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8',
        duration: '3:15',
        source: 'YouTube',
        url: 'https://example.com/happy-video-2',
      },
      {
        id: 'happy-video-3',
        title: 'Comedians Share Their Happiest Moments',
        thumbnailUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad',
        duration: '8:20',
        source: 'YouTube',
        url: 'https://example.com/happy-video-3',
      },
    ],
  },
  sad: {
    title: 'Comfort Corner',
    emoji: '😢',
    quotes: [
      "Even the darkest night will end and the sun will rise.",
      "In the midst of winter, I found there was, within me, an invincible summer.",
      "The wound is the place where the light enters you.",
      "There is a crack in everything, that's how the light gets in.",
      "We must embrace pain and burn it as fuel for our journey."
    ],
    articles: [
      {
        id: 'sad-1',
        title: 'Finding Meaning Through Difficult Times',
        excerpt: 'How challenges can lead to personal growth and deeper understanding of yourself and others.',
        imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e',
        source: 'Psychology Today',
        url: 'https://example.com/sad-article-1',
      },
      {
        id: 'sad-2',
        title: 'The Power of Emotional Processing',
        excerpt: 'Why allowing yourself to feel sad can actually be healthy and healing in the long run.',
        imageUrl: 'https://images.unsplash.com/photo-1444069069607-8a78508ecc36',
        source: 'Mental Health Journal',
        url: 'https://example.com/sad-article-2',
      },
      {
        id: 'sad-3',
        title: 'Rainy Day Reflections',
        excerpt: 'Using melancholy moments as opportunities for deep reflection and personal insight.',
        imageUrl: 'https://images.unsplash.com/photo-1498036882173-b41c28a8ba34',
        source: 'Mindful Thinking',
        url: 'https://example.com/sad-article-3',
      },
    ],
    playlists: [
      {
        id: 'sad-playlist-1',
        name: 'Rainy Day Acoustics',
        description: 'Gentle acoustic songs for a reflective mood',
        coverUrl: 'https://images.unsplash.com/photo-1501999635878-71cb5379c2d8',
        sourceUrl: 'https://example.com/sad-playlist-1',
        source: 'Spotify',
      },
      {
        id: 'sad-playlist-2',
        name: 'Melancholy Piano',
        description: 'Beautiful piano compositions for emotional moments',
        coverUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0',
        sourceUrl: 'https://example.com/sad-playlist-2',
        source: 'Apple Music',
      },
      {
        id: 'sad-playlist-3',
        name: 'Soothing Ambient',
        description: 'Atmospheric sounds to help process emotions',
        coverUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        sourceUrl: 'https://example.com/sad-playlist-3',
        source: 'YouTube Music',
      },
      {
        id: 'sad-playlist-4',
        name: 'Poetic Lyrics',
        description: 'Songs with meaningful lyrics that resonate with deeper feelings',
        coverUrl: 'https://images.unsplash.com/photo-1485579149621-3123dd979885',
        sourceUrl: 'https://example.com/sad-playlist-4',
        source: 'Spotify',
      },
    ],
    videos: [
      {
        id: 'sad-video-1',
        title: 'How to Cope with Difficult Emotions',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517677129300-07b130802f46',
        duration: '7:15',
        source: 'YouTube',
        url: 'https://example.com/sad-video-1',
      },
      {
        id: 'sad-video-2',
        title: 'Guided Meditation for Emotional Healing',
        thumbnailUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773',
        duration: '15:42',
        source: 'YouTube',
        url: 'https://example.com/sad-video-2',
      },
      {
        id: 'sad-video-3',
        title: 'Finding Hope During Difficult Times',
        thumbnailUrl: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94',
        duration: '10:18',
        source: 'YouTube',
        url: 'https://example.com/sad-video-3',
      },
    ],
  },
  energetic: {
    title: 'Power Zone',
    emoji: '⚡',
    quotes: [
      "Energy and persistence conquer all things.",
      "Success is going from failure to failure without losing your enthusiasm.",
      "Don't watch the clock; do what it does. Keep going.",
      "The higher your energy level, the more efficient your body. The more efficient your body, the better you feel.",
      "Action is the foundational key to all success."
    ],
    articles: [
      {
        id: 'energetic-1',
        title: 'How to Maintain High Energy Throughout Your Day',
        excerpt: 'Practical tips for sustaining energy levels without relying on caffeine or sugar.',
        imageUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5',
        source: 'Productivity Hub',
        url: 'https://example.com/energetic-article-1',
      },
      {
        id: 'energetic-2',
        title: 'The Power of Dynamic Movement',
        excerpt: 'How incorporating more movement into your day can boost both physical and mental energy.',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b',
        source: 'Fitness Journal',
        url: 'https://example.com/energetic-article-2',
      },
      {
        id: 'energetic-3',
        title: 'Foods That Fuel Your Brain',
        excerpt: 'The best nutrients and eating patterns to optimize your cognitive performance and energy.',
        imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061',
        source: 'Nutrition Science',
        url: 'https://example.com/energetic-article-3',
      },
    ],
    playlists: [
      {
        id: 'energetic-playlist-1',
        name: 'Workout Motivation',
        description: 'High BPM tracks to power through any workout',
        coverUrl: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c',
        sourceUrl: 'https://example.com/energetic-playlist-1',
        source: 'Spotify',
      },
      {
        id: 'energetic-playlist-2',
        name: 'Productivity Boost',
        description: 'Upbeat instrumental tracks to help you focus and get things done',
        coverUrl: 'https://images.unsplash.com/photo-1483058712412-4245e9b90334',
        sourceUrl: 'https://example.com/energetic-playlist-2',
        source: 'Apple Music',
      },
      {
        id: 'energetic-playlist-3',
        name: 'Morning Power Hour',
        description: 'The perfect soundtrack to kick-start your day with energy',
        coverUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
        sourceUrl: 'https://example.com/energetic-playlist-3',
        source: 'YouTube Music',
      },
      {
        id: 'energetic-playlist-4',
        name: 'Electronic Energy',
        description: 'Driving electronic beats to keep you moving',
        coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745',
        sourceUrl: 'https://example.com/energetic-playlist-4',
        source: 'Spotify',
      },
    ],
    videos: [
      {
        id: 'energetic-video-1',
        title: '5-Minute Energy-Boosting Workout',
        thumbnailUrl: 'https://images.unsplash.com/photo-1607962837359-5e7e89f86776',
        duration: '5:05',
        source: 'YouTube',
        url: 'https://example.com/energetic-video-1',
      },
      {
        id: 'energetic-video-2',
        title: 'How to Create a High-Energy Morning Routine',
        thumbnailUrl: 'https://images.unsplash.com/photo-1555212697-194d092e3b8f',
        duration: '8:34',
        source: 'YouTube',
        url: 'https://example.com/energetic-video-2',
      },
      {
        id: 'energetic-video-3',
        title: 'Biohacking Your Energy Levels',
        thumbnailUrl: 'https://images.unsplash.com/photo-1550831858-3c2581fed470',
        duration: '12:47',
        source: 'YouTube',
        url: 'https://example.com/energetic-video-3',
      },
    ],
  },
  calm: {
    title: 'Tranquil Space',
    emoji: '😌',
    quotes: [
      "Peace comes from within. Do not seek it without.",
      "Within you, there is a stillness and a sanctuary to which you can retreat at any time.",
      "The best remedy for those who are afraid, lonely or unhappy is to go outside.",
      "Calm mind brings inner strength and self-confidence.",
      "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor."
    ],
    articles: [
      {
        id: 'calm-1',
        title: 'The Science Behind Meditation and Inner Peace',
        excerpt: 'How regular meditation practice physically changes your brain and reduces stress.',
        imageUrl: 'https://images.unsplash.com/photo-1515894274780-8f7b92789868',
        source: 'Mindfulness Research',
        url: 'https://example.com/calm-article-1',
      },
      {
        id: 'calm-2',
        title: 'Creating a Calming Home Environment',
        excerpt: 'Simple changes to your living space that can promote feelings of tranquility and ease.',
        imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
        source: 'Mindful Living',
        url: 'https://example.com/calm-article-2',
      },
      {
        id: 'calm-3',
        title: 'The Art of Slow Living',
        excerpt: 'How embracing a slower pace can lead to greater fulfillment and presence in life.',
        imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773',
        source: 'Wellness Journal',
        url: 'https://example.com/calm-article-3',
      },
    ],
    playlists: [
      {
        id: 'calm-playlist-1',
        name: 'Meditation Soundscapes',
        description: 'Gentle ambient sounds to aid meditation and relaxation',
        coverUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4',
        sourceUrl: 'https://example.com/calm-playlist-1',
        source: 'Spotify',
      },
      {
        id: 'calm-playlist-2',
        name: 'Sleep Well',
        description: 'Soothing sounds to help you fall asleep peacefully',
        coverUrl: 'https://images.unsplash.com/photo-1455642305367-68834a9c8827',
        sourceUrl: 'https://example.com/calm-playlist-2',
        source: 'Apple Music',
      },
      {
        id: 'calm-playlist-3',
        name: 'Gentle Classical',
        description: 'Soft classical compositions for relaxation',
        coverUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76',
        sourceUrl: 'https://example.com/calm-playlist-3',
        source: 'YouTube Music',
      },
      {
        id: 'calm-playlist-4',
        name: 'Nature Sounds',
        description: 'Authentic recordings from forests, oceans, and rainstorms',
        coverUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
        sourceUrl: 'https://example.com/calm-playlist-4',
        source: 'Spotify',
      },
    ],
    videos: [
      {
        id: 'calm-video-1',
        title: '10-Minute Guided Meditation for Inner Peace',
        thumbnailUrl: 'https://images.unsplash.com/photo-1591228127791-8e2eaef098d3',
        duration: '10:12',
        source: 'YouTube',
        url: 'https://example.com/calm-video-1',
      },
      {
        id: 'calm-video-2',
        title: 'Gentle Yoga for Stress Relief',
        thumbnailUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773',
        duration: '18:30',
        source: 'YouTube',
        url: 'https://example.com/calm-video-2',
      },
      {
        id: 'calm-video-3',
        title: 'The Art of Tea Meditation',
        thumbnailUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f',
        duration: '7:50',
        source: 'YouTube',
        url: 'https://example.com/calm-video-3',
      },
    ],
  },
  angry: {
    title: 'Cooling Station',
    emoji: '😠',
    quotes: [
      "For every minute you remain angry, you give up sixty seconds of peace of mind.",
      "When angry, count to ten before you speak. If very angry, count to one hundred.",
      "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.",
      "Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.",
      "Speak when you are angry and you will make the best speech you will ever regret."
    ],
    articles: [
      {
        id: 'angry-1',
        title: 'Healthy Ways to Process and Release Anger',
        excerpt: 'Techniques for acknowledging anger and channeling it into constructive outlets.',
        imageUrl: 'https://images.unsplash.com/photo-1541199249251-f713e6145474',
        source: 'Emotional Health',
        url: 'https://example.com/angry-article-1',
      },
      {
        id: 'angry-2',
        title: 'The Physical Effects of Anger on Your Body',
        excerpt: 'Understanding how anger impacts your physical health and what you can do about it.',
        imageUrl: 'https://images.unsplash.com/photo-1580893246395-52aead8960dc',
        source: 'Health Research',
        url: 'https://example.com/angry-article-2',
      },
      {
        id: 'angry-3',
        title: 'Transforming Anger Into Creative Energy',
        excerpt: 'How to harness the powerful energy of anger for positive change and creative expression.',
        imageUrl: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91',
        source: 'Creative Psychology',
        url: 'https://example.com/angry-article-3',
      },
    ],
    playlists: [
      {
        id: 'angry-playlist-1',
        name: 'Healthy Release',
        description: 'High-energy tracks to help process and release tension',
        coverUrl: 'https://images.unsplash.com/photo-1509335919046-c96d2490bcdf',
        sourceUrl: 'https://example.com/angry-playlist-1',
        source: 'Spotify',
      },
      {
        id: 'angry-playlist-2',
        name: 'Cathartic Classics',
        description: 'Powerful music that helps express and process intense emotions',
        coverUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d',
        sourceUrl: 'https://example.com/angry-playlist-2',
        source: 'Apple Music',
      },
      {
        id: 'angry-playlist-3',
        name: 'Cooling Transition',
        description: 'Music that helps transition from anger to calmer states',
        coverUrl: 'https://images.unsplash.com/photo-1458560871784-56d23406c091',
        sourceUrl: 'https://example.com/angry-playlist-3',
        source: 'YouTube Music',
      },
      {
        id: 'angry-playlist-4',
        name: 'Rhythmic Therapy',
        description: 'Rhythmic beats to help process emotions through movement',
        coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42',
        sourceUrl: 'https://example.com/angry-playlist-4',
        source: 'Spotify',
      },
    ],
    videos: [
      {
        id: 'angry-video-1',
        title: '5-Minute Anger Release Exercise',
        thumbnailUrl: 'https://images.unsplash.com/photo-1545389336-cf090694435e',
        duration: '5:28',
        source: 'YouTube',
        url: 'https://example.com/angry-video-1',
      },
      {
        id: 'angry-video-2',
        title: 'Understanding the Root Causes of Anger',
        thumbnailUrl: 'https://images.unsplash.com/photo-1542596768-5d1d21f1cf98',
        duration: '11:15',
        source: 'YouTube',
        url: 'https://example.com/angry-video-2',
      },
      {
        id: 'angry-video-3',
        title: 'Mindfulness Techniques for Anger Management',
        thumbnailUrl: 'https://images.unsplash.com/photo-1474418397713-003ec9d2c414',
        duration: '9:40',
        source: 'YouTube',
        url: 'https://example.com/angry-video-3',
      },
    ],
  },
};

// Sample shop items
export const shopItems: ShopItem[] = [
  {
    id: 'shop-1',
    name: 'Happiness Journal',
    description: 'A guided journal with prompts to help you focus on the positive aspects of your day and cultivate gratitude.',
    imageUrl: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57',
    price: 14.99,
    category: 'Books',
    moodTags: ['happy', 'calm'],
  },
  {
    id: 'shop-2',
    name: 'Energizing Essential Oil Blend',
    description: 'A vibrant blend of citrus and mint essential oils designed to invigorate your senses and boost energy.',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108',
    price: 18.50,
    category: 'Wellness',
    moodTags: ['energetic', 'happy'],
  },
  {
    id: 'shop-3',
    name: 'Calming Weighted Blanket',
    description: 'A premium weighted blanket that provides gentle pressure to help reduce anxiety and improve sleep quality.',
    imageUrl: 'https://images.unsplash.com/photo-1584470651377-ea0b1249a2d7',
    price: 79.99,
    category: 'Decor',
    moodTags: ['calm', 'sad'],
  },
  {
    id: 'shop-4',
    name: 'Mindfulness Meditation Cushion',
    description: 'Ergonomically designed meditation cushion to support proper posture during meditation sessions.',
    imageUrl: 'https://images.unsplash.com/photo-1536623975707-c4b3b2af565d',
    price: 39.95,
    category: 'Wellness',
    moodTags: ['calm', 'angry'],
  },
  {
    id: 'shop-5',
    name: 'High-Energy Fitness Box',
    description: 'Monthly subscription box with fitness equipment, healthy snacks, and workout plans.',
    imageUrl: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba',
    price: 49.99,
    category: 'Wellness',
    moodTags: ['energetic', 'happy'],
  },
  {
    id: 'shop-6',
    name: 'Comforting Tea Collection',
    description: 'Set of 5 premium herbal teas scientifically formulated to calm the mind and soothe the soul.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3',
    price: 24.95,
    category: 'Wellness',
    moodTags: ['sad', 'calm'],
  },
  {
    id: 'shop-7',
    name: 'Anger Management Toolkit',
    description: 'A collection of tools, exercises, and resources designed to help manage and channel anger effectively.',
    imageUrl: 'https://images.unsplash.com/photo-1609942072467-a364d4d3297f',
    price: 32.99,
    category: 'Books',
    moodTags: ['angry'],
  },
  {
    id: 'shop-8',
    name: 'Sunrise Alarm Clock',
    description: 'Wake up naturally with this alarm clock that simulates sunrise, helping regulate your mood throughout the day.',
    imageUrl: 'https://images.unsplash.com/photo-1531379410502-63bfe8cdaf6f',
    price: 45.00,
    category: 'Tech',
    moodTags: ['happy', 'energetic', 'sad'],
  },
  {
    id: 'shop-9',
    name: 'Motivational Wall Art Set',
    description: 'Set of 3 inspirational prints to keep you motivated and focused on your goals.',
    imageUrl: 'https://images.unsplash.com/photo-1555212697-194d092e3b8f',
    price: 29.99,
    category: 'Decor',
    moodTags: ['energetic', 'happy'],
  },
  {
    id: 'shop-10',
    name: 'Cozy Reading Socks',
    description: 'Ultra-soft, warm socks perfect for curling up with a good book on a rainy day.',
    imageUrl: 'https://images.unsplash.com/photo-1586495985096-787fb4a54ac0',
    price: 12.50,
    category: 'Clothing',
    moodTags: ['sad', 'calm'],
  },
  {
    id: 'shop-11',
    name: 'Smart Mood Tracking Wearable',
    description: 'Wristband that monitors physiological signals to help you understand and improve your emotional patterns.',
    imageUrl: 'https://images.unsplash.com/photo-1510017803434-a899398421b3',
    price: 89.99,
    category: 'Tech',
    moodTags: ['happy', 'sad', 'energetic', 'calm', 'angry'],
  },
  {
    id: 'shop-12',
    name: 'Therapeutic Art Kit',
    description: 'Complete art therapy kit with supplies and guided exercises to express and process emotions creatively.',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f',
    price: 34.95,
    category: 'Wellness',
    moodTags: ['angry', 'sad', 'happy'],
  },
];